Traceback (most recent call last):
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/scrutycs/uni/5-Semester/ASUMR/venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
def main():
    env = Environment(6)
    markov = Agent(env)
    AgentVizualizer(markov, num_steps=9)()


if __name__ == '__main__':
    main()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[5], line 8[0m
[1;32m      4[0m     AgentVizualizer(markov, num_steps[38;5;241m=[39m[38;5;241m9[39m)()
[1;32m      7[0m [38;5;28;01mif[39;00m [38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m'[39m[38;5;124m__main__[39m[38;5;124m'[39m:
[0;32m----> 8[0m     [43mmain[49m[43m([49m[43m)[49m

Cell [0;32mIn[5], line 4[0m, in [0;36mmain[0;34m()[0m
[1;32m      2[0m env [38;5;241m=[39m Environment([38;5;241m6[39m)
[1;32m      3[0m markov [38;5;241m=[39m Agent(env)
[0;32m----> 4[0m [43mAgentVizualizer[49m[43m([49m[43mmarkov[49m[43m,[49m[43m [49m[43mnum_steps[49m[38;5;241;43m=[39;49m[38;5;241;43m9[39;49m[43m)[49m[43m([49m[43m)[49m

Cell [0;32mIn[4], line 23[0m, in [0;36mAgentVizualizer.__call__[0;34m(self)[0m
[1;32m     20[0m [38;5;28;01mfor[39;00m i, (bel, pos) [38;5;129;01min[39;00m [38;5;28menumerate[39m([38;5;28mself[39m[38;5;241m.[39magent([38;5;28mself[39m[38;5;241m.[39mnum_steps)):
[1;32m     21[0m     ax [38;5;241m=[39m axs_flat[i]
[0;32m---> 23[0m     x, y [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43minterpol_bel[49m[43m([49m[43mbel[49m[43m)[49m
[1;32m     24[0m     ax[38;5;241m.[39mscatter(pos, [38;5;241m0[39m, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mred[39m[38;5;124m'[39m)
[1;32m     25[0m     ax[38;5;241m.[39mplot(x, y, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblue[39m[38;5;124m'[39m)

Cell [0;32mIn[4], line 11[0m, in [0;36mAgentVizualizer.interpol_bel[0;34m(self, bel)[0m
[1;32m      9[0m x [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;28mself[39m[38;5;241m.[39msize, [38;5;28mlen[39m(bel))
[1;32m     10[0m y [38;5;241m=[39m bel
[0;32m---> 11[0m f [38;5;241m=[39m [43minterp1d[49m(x, y, kind[38;5;241m=[39m[38;5;124m'[39m[38;5;124mnearest[39m[38;5;124m'[39m, fill_value[38;5;241m=[39m[38;5;124m'[39m[38;5;124mextrapolate[39m[38;5;124m'[39m)
[1;32m     12[0m x_new [38;5;241m=[39m np[38;5;241m.[39mlinspace([38;5;241m0[39m, [38;5;28mself[39m[38;5;241m.[39msize, [38;5;241m100[39m)
[1;32m     13[0m y_new [38;5;241m=[39m f(x_new)

[0;31mNameError[0m: name 'interp1d' is not defined

